const cardTable = [
    {
        id: '444',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/table/rodos_white_330.png 330w, ./images/mob/card-product/table/rodos_white@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/table/rodos_white_330.png",
        alt: "table rodos white",
        name: "Table rodos white",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00000",
    },
    {
        id: '555',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/table/mykolaev_330.png 330w, ./images/mob/card-product/table/mykolaev@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/table/mykolaev_330.png",
        alt: "table 'mykolaev'",
        name: "Table 'mykolaev'",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00000",
    },
    {
        id: '.....',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/table/rodos_red_330.png 330w, ./images/mob/card-product/table/rodos_red@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/table/rodos_red_330.png",
        alt: "table rodos red",
        name: "Table rodos red",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00000",
    },
    {
        id: '.....',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/table/rodos_table_dark-gray_330.png 330w, ./images/mob/card-product/table/rodos_table_dark-gray@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/table/rodos_table_dark-gray_330.png",
        alt: "table rodos dark-gray",
        name: "Table rodos dark-gray",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00000",
    },
    {
        id: '.....',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/table/rodos_table_wooden_and_white_330.png 330w, ./images/mob/card-product/table/rodos_table_wooden_and_white@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/table/rodos_table_wooden_and_white_330.png",
        alt: "table rodos wooden and white",
        name: "Table rodos wooden and white",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00000",
    },
    {
        id: '.....',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/table/rodos_table_dark-gray2_330.png 330w, ./images/mob/card-product/table/rodos_table_dark-gray2@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/table/rodos_table_dark-gray2_330.png",
        alt: "table rodos dark-gray",
        name: "Table rodos dark-gray",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00000",
    },
    {
        id: '555',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/table/rodos_table_light-gray_330.png 330w, ./images/mob/card-product/table/rodos_table_light-gray@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/table/rodos_table_light-gray_330.png",
        alt: "table rodos light-gray",
        name: "Table rodos light-gray",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00000",
    },
    {
        id: '555',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/table/rodos_table_wooden_and_black_330.png 330w, ./images/mob/card-product/table/rodos_table_wooden_and_black@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/table/rodos_table_wooden_and_black_330.png",
        alt: "table rodos wooden and black",
        name: "Table rodos wooden and black",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00000",
    },
]

export default cardTable