// import { v4 as uuidv4 } from 'uuid'

const cardPouf = [
    {
        id: '111',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/poufs/pink_pouf_330.png 330w, ./images/mob/card-product/poufs/pink_pouf@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/poufs/pink_pouf_330.png",
        alt: "pink pouf",
        name: "Pink pouf",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00001",
    },
    {
        id: '222',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/poufs/black_pouf_330.png 330w, ./images/mob/card-product/poufs/black_pouf@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/poufs/black_pouf_330.png",
        alt: "black pouf",
        name: "Black pouf",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00002",
    },
    {
        id: '333',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/poufs/gray_pouf_330.png 330w, ./images/mob/card-product/poufs/gray_pouf@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/poufs/gray_pouf_330.png",
        alt: "gray pouf",
        name: "Gray pouf",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00003",
    },
    {
        id: '444',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/poufs/blue_pouf_330.png 330w, ./images/mob/card-product/poufs/blue_pouf@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/poufs/blue_pouf_330.png",
        alt: "blue pouf",
        name: "Blue pouf",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00004",
    },
    {
        id: '555',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/poufs/green_pouf_330.png 330w, ./images/mob/card-product/poufs/green_pouf@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/poufs/green_pouf_330.png",
        alt: "green pouf",
        name: "Green pouf",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00005",
    },
    {
        id: '777',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/poufs/terracotta_pouf_330.png 330w, ./images/mob/card-product/poufs/terracotta_pouf@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/poufs/terracotta_pouf_330.png",
        alt: "terracotta pouf",
        name: "Terracotta pouf",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00006",
    },
    {
        id: '888',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/poufs/multicolored_pouf_330.png 330w, ./images/mob/card-product/poufs/multicolored_pouf@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/poufs/multicolored_pouf_330.png",
        alt: "multicolored pouf",
        name: "Multicolored pouf",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00007",
    },
    {
        id: '999',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/poufs/dark-gray_pouf_330.png 330w, ./images/mob/card-product/poufs/dark-gray_pouf@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/poufs/dark-gray_pouf_330.png",
        alt: "dark-gray pouf",
        name: "Dark-gray pouf",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00008",
    },
    {
        id: '101010',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/poufs/pink-gray_pouf_330.png 330w, ./images/mob/card-product/poufs/pink-gray_pouf@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/poufs/pink-gray_pouf_330.png",
        alt: "pink-gray pouf",
        name: "Pink-gray pouf",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00009",
    },
    {
        id: '111111',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/poufs/light-green_pouf_330.png 330w, ./images/mob/card-product/poufs/light-green_pouf@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/poufs/light-green_pouf_330.png",
        alt: "light-green pouf",
        name: "Light-green pouf",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00010",
    },
    {
        id: '121212',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/poufs/white_pouf_330.png 330w, ./images/mob/card-product/poufs/white_pouf@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/poufs/white_pouf_330.png",
        alt: "white pouf",
        name: "White pouf",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00011",
    },
    {
        id: '131313',
        // id: uuidv4(),
        srcset: "./images/mob/card-product/poufs/yellow_pouf_330.png 330w, ./images/mob/card-product/poufs/yellow_pouf@2_330.png 660w",
        sizes: "(min-width: 375px) 330px, 100vw",
        src: "./images/mob/card-product/poufs/yellow_pouf_330.png",
        alt: "yellow pouf",
        name: "Yellow pouf",
        description: "Lorem ipsum dolor sit amet consectetur. Odio sit molestie erat eget quam tellus ipsum nibh.Arcu integer mi massa nascetur tristique vitae euismod ut in.Urna mauris habitant augue senectus tellus venenatis nibh.Amet orci sed et placerat.Enim aliquet morbi ultricies consectetur.Quis sed volutpat enim enim.",
        price: "9000 грн",
        artNum: "№00012",
    },
]

export default cardPouf